import type { GeneratedExperience, GeneratedResume } from '@/types/resume'

/**
 * Ordered replacements: multi-word and longer tokens first to avoid partial mangling.
 * Uses word boundaries where safe so we don’t alter unrelated words.
 */
const PAIRS: Array<[RegExp, string]> = [
  [/technical\s+seo\b/gi, 'Technical SEO'],
  [/on-?page\s+seo\b/gi, 'On-page SEO'],
  [/google\s+tag\s+manager\b/gi, 'Google Tag Manager'],
  [/google\s+analytics\b/gi, 'Google Analytics'],
  [/core\s+web\s+vitals\b/gi, 'Core Web Vitals'],
  [/material\s+ui\b/gi, 'Material UI'],
  [/adobe\s+creative\s+suite\b/gi, 'Adobe Creative Suite'],
  [/node\.js\b/gi, 'Node.js'],
  [/\bnodejs\b/gi, 'Node.js'],
  [/next\.js\b/gi, 'Next.js'],
  [/nuxt\.js\b/gi, 'Nuxt.js'],
  [/vue\.js\b/gi, 'Vue.js'],
  [/react\.js\b/gi, 'React'],
  [/rest\s+api\b/gi, 'REST API'],
  [/graphql\b/gi, 'GraphQL'],
  [/ci\/cd\b/gi, 'CI/CD'],
  [/woocommerce\b/gi, 'WooCommerce'],
  [/wordpress\b/gi, 'WordPress'],
  [/javascript\b/gi, 'JavaScript'],
  [/typescript\b/gi, 'TypeScript'],
  [/tailwind\s+css\b/gi, 'Tailwind CSS'],
  [/\btailwind\b/gi, 'Tailwind CSS'],
  [/web\s*flow\b/gi, 'Webflow'],
  [/squarespace\b/gi, 'Squarespace'],
  [/contentful\b/gi, 'Contentful'],
  [/sanity\.io\b/gi, 'Sanity'],
  [/storybook\b/gi, 'Storybook'],
  [/webpack\b/gi, 'Webpack'],
  [/\bvite\b/gi, 'Vite'],
  [/eslint\b/gi, 'ESLint'],
  [/\bjest\b/gi, 'Jest'],
  [/cypress\b/gi, 'Cypress'],
  [/playwright\b/gi, 'Playwright'],
  [/github\s+actions\b/gi, 'GitHub Actions'],
  [/github\b/gi, 'GitHub'],
  [/gitlab\b/gi, 'GitLab'],
  [/bitbucket\b/gi, 'Bitbucket'],
  [/atlassian\b/gi, 'Atlassian'],
  [/\bjira\b/gi, 'Jira'],
  [/confluence\b/gi, 'Confluence'],
  [/figma\b/gi, 'Figma'],
  [/\bslack\b/gi, 'Slack'],
  [/hubspot\b/gi, 'HubSpot'],
  [/salesforce\b/gi, 'Salesforce'],
  [/marketo\b/gi, 'Marketo'],
  [/mailchimp\b/gi, 'Mailchimp'],
  [/zendesk\b/gi, 'Zendesk'],
  [/intercom\b/gi, 'Intercom'],
  [/stripe\b/gi, 'Stripe'],
  [/paypal\b/gi, 'PayPal'],
  [/shopify\b/gi, 'Shopify'],
  [/magento\b/gi, 'Magento'],
  [/bigcommerce\b/gi, 'BigCommerce'],
  [/drupal\b/gi, 'Drupal'],
  [/laravel\b/gi, 'Laravel'],
  [/symfony\b/gi, 'Symfony'],
  [/django\b/gi, 'Django'],
  [/rails\b/gi, 'Rails'],
  [/ruby\s+on\s+rails\b/gi, 'Ruby on Rails'],
  [/spring\s+boot\b/gi, 'Spring Boot'],
  [/asp\.net\b/gi, 'ASP.NET'],
  [/\bphp\b/gi, 'PHP'],
  [/\bmysql\b/gi, 'MySQL'],
  [/postgresql\b/gi, 'PostgreSQL'],
  [/\bpostgres\b/gi, 'PostgreSQL'],
  [/mongodb\b/gi, 'MongoDB'],
  [/redis\b/gi, 'Redis'],
  [/elasticsearch\b/gi, 'Elasticsearch'],
  [/dynamodb\b/gi, 'DynamoDB'],
  [/kubernetes\b/gi, 'Kubernetes'],
  [/\bk8s\b/g, 'Kubernetes'],
  [/docker\b/gi, 'Docker'],
  [/terraform\b/gi, 'Terraform'],
  [/ansible\b/gi, 'Ansible'],
  [/jenkins\b/gi, 'Jenkins'],
  [/circleci\b/gi, 'CircleCI'],
  [/travis\s*ci\b/gi, 'Travis CI'],
  [/new\s+relic\b/gi, 'New Relic'],
  [/datadog\b/gi, 'Datadog'],
  [/sentry\b/gi, 'Sentry'],
  [/splunk\b/gi, 'Splunk'],
  [/\baws\b/g, 'AWS'],
  [/amazon\s+ecs\b/gi, 'Amazon ECS'],
  [/amazon\s+ecr\b/gi, 'Amazon ECR'],
  [/amazon\s+s3\b/gi, 'Amazon S3'],
  [/lambda\b/gi, 'Lambda'],
  [/cloudfront\b/gi, 'CloudFront'],
  [/azure\b/gi, 'Azure'],
  [/\bgcp\b/g, 'GCP'],
  [/google\s+cloud\b/gi, 'Google Cloud'],
  [/firebase\b/gi, 'Firebase'],
  [/vercel\b/gi, 'Vercel'],
  [/netlify\b/gi, 'Netlify'],
  [/cloudflare\b/gi, 'Cloudflare'],
  [/fastly\b/gi, 'Fastly'],
  [/akamai\b/gi, 'Akamai'],
  [/gutenberg\b/gi, 'Gutenberg'],
  [/advanced\s+custom\s+fields\b/gi, 'Advanced Custom Fields'],
  [/\bacf\b/g, 'ACF'],
  [/elementor\b/gi, 'Elementor'],
  [/divi\b/gi, 'Divi'],
  [/jquery\b/gi, 'jQuery'],
  [/\breact\b/gi, 'React'],
  [/\bangular\b/gi, 'Angular'],
  [/\bsvelte\b/gi, 'Svelte'],
  [/redux\b/gi, 'Redux'],
  [/zustand\b/gi, 'Zustand'],
  [/rxjs\b/gi, 'RxJS'],
  [/\bhtml5?\b/gi, 'HTML'],
  [/\bcss3?\b/gi, 'CSS'],
  [/\bsass\b/gi, 'Sass'],
  [/\bscss\b/gi, 'SCSS'],
  [/\bajax\b/gi, 'Ajax'],
  [/\bjson\b/gi, 'JSON'],
  [/\bxml\b/gi, 'XML'],
  [/\byaml\b/gi, 'YAML'],
  [/\bseo\b/gi, 'SEO'],
  [/\bsem\b/gi, 'SEM'],
  [/\bppc\b/gi, 'PPC'],
  [/\bcrm\b/gi, 'CRM'],
  [/\bcta\b/gi, 'CTA'],
  [/\bui\b/g, 'UI'],
  [/\bux\b/g, 'UX'],
  [/\bapi\b/gi, 'API'],
  [/\bgdpr\b/gi, 'GDPR'],
  [/\bwcag\b/gi, 'WCAG'],
  [/\ba\/b\s+test(?:ing)?\b/gi, 'A/B testing'],
  [/\bga4\b/g, 'GA4'],
]

/** Normalize product names, languages, and common acronyms in résumé copy. */
export function normalizeResumeCopyText(text: string): string {
  if (!text) return text
  let s = text
  for (const [pattern, replacement] of PAIRS) {
    s = s.replace(pattern, replacement)
  }
  return s
}

export function normalizeExperienceCopy(experiences: GeneratedExperience[]): GeneratedExperience[] {
  return experiences.map((exp) => ({
    ...exp,
    role_title: normalizeResumeCopyText(exp.role_title),
    responsibilities: exp.responsibilities.map((r) => normalizeResumeCopyText(r)),
  }))
}

export function normalizeGeneratedResume(resume: GeneratedResume): GeneratedResume {
  return {
    ...resume,
    candidate: {
      ...resume.candidate,
      headline: resume.candidate.headline ? normalizeResumeCopyText(resume.candidate.headline) : resume.candidate.headline,
      summary: resume.candidate.summary ? normalizeResumeCopyText(resume.candidate.summary) : resume.candidate.summary,
    },
    sections: {
      core_skills_text: normalizeResumeCopyText(resume.sections.core_skills_text),
      education_text: normalizeResumeCopyText(resume.sections.education_text),
    },
    experience: normalizeExperienceCopy(resume.experience),
  }
}
